dstore/cartapp/urls.py
from django.urls import path
from cartapp import views
app_name='cartapp'

urlpatterns=[
    path('add/', views.add_cart, name="add_cart"),
    path('add-item/<int:product_id>', views.add_item, name="add_item"),
    path('cart/',views.cart_detail,name="cart_detail"),
    path('remove/<int:product_id>', views.remove_item, name="remove_item"),
    path('delete/<int:product_id>', views.delete_item, name="delete_item"),

]

dstore/dstore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('homeapp.urls')),
    path('cart/', include('cartapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

dstore/homeapp/urls.py
from django.contrib import admin
from django.urls import path
from homeapp import views
app_name='homeapp'

urlpatterns = [
    path('index', views.index,name='index'),
    path('about', views.about, name='about'),
    path('ajax/load-courses/', views.load_courses, name='ajax_load_courses'),
    path('shope', views.shope, name='shope'),

    #urls for auth
    path('register/', views.register,name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

    #urls for store
    path('paymsg', views.paymsg, name='paymsg'),
]

dstore/homeapp/models.py
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description =models.TextField(blank=True)
    image = models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('homeapp:Products_of_Category',kwargs={"c_slug": self.slug})

    def __str__(self):
        return  '{}'.format(self.name)

class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description =models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product',blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('homeapp:get_product_details', kwargs={"c_slug": self.category.slug,"p_slug":self.slug})

    def __str__(self):
        return '{}'.format(self.name)

class Department(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Course(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Profile(models.Model):

    Purpose = (
        ('enquiry', "Enquiry"),
        ('placeorder', "Place order"),
        ('return', "Return")
    )

    name=models.CharField(max_length=100)
    dob=models.DateField(auto_now_add=False,auto_now=False)
    age=models.PositiveIntegerField(default=False,
        validators=[MaxValueValidator(60), MinValueValidator(10)])
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    Gender = (('Male', 'Male'), ('Female', 'Female'))
    gender = models.CharField(max_length=100, choices=Gender, blank=False, default=None)
    phone = models.PositiveBigIntegerField()
    mailid = models.EmailField(max_length=100)
    address = models.CharField(max_length=500)
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True)
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)
    purpose = models.CharField(max_length=100,choices=Purpose)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'profile'
        verbose_name_plural = 'profiles'


    def __str__(self):
        return '{}'.format(self.name)

dstore/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
  <div class="card mt-5">
    <div class="card-body">
      <div class="card-title text-center" ><h3>ABOUT US</h3></div>
      <p>sint Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus optio sectetur minima soluta nulla, alias tenetur doloribus vitae quo eaque, quae illo!fugit tempora ipsum maiores dolorum enim, beatae qui quasisint Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus optio sectetur minima soluta nulla, alias tenetur doloribus vitae quo eaque, quae illo!fugit tempora ipsum maiores dolorum enim, beatae qui quasi</p>
    </div>
  </div>
</div>



<div class="container text-center">
  <div class="row mt-5">
    <div class="col-sm-4">
      <h4>MISSION</h4>
      <p>Lorem ipsum dolor sit amet, consealias tenetur doloribus vitae quo eaque, quae illo!fugit tempora ipsum maiores dolorum enim, beatae qui quasialias tenetur doloribus vitae quo eaque, quae illo!fugit tempora ipsum maiores dolorum enim, beatae qui quasictetur adipisicing elit. Ducimus optio</p>
    </div>
    <div class="col-sm-4">
      <h4>VISSION</h4>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus optio sectetur minima soluta nulla, alias tenetur doloribus vitae quo eaque, quae illo!fugit tempora ipsum maiores dolorum enim, beatae qui quasialias tenetur doloribus vitae quo eaque, quae illo!fugit tempora ipsum maiores</p>
    </div>
    <div class="col-sm-4">
      <h4>ACHIEVEMENTS</h4>
      <p>sint Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus optio sectetur minima soluta doloribus vitae quo eaque, quae illo!fugit tempora ipsum maiores dolorum enim, be doloribus vitae quo eaque, quae illo!fugit tempora ipsum maiores dolorum enim, beatae qui quasi</p>
    </div>
  </div>
</div><br>

{% endblock  %}

dstore/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        This is the cart page. Proceed to review your items and place the order.
{% endblock %}

{% block title %}
    Cart - DSTORE pvt lmt
{% endblock %}



{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your shopping cart is empty </h1>
        <br>
        <p class="text-center"> Please click <a href="{% url 'ecartapp:allProdCat' %}">Here</a>to continue shopping.</p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your shopping cart</h1>
        <br>
    </div>
</div>
<div class="row mx_auto">
    <div class="col-12 col-md-12 col-sm-12 col-lg-6 text-center">
        <table class="my_custom_table">
            <thead class="my_custom_thead">
                <tr><th colspan="5">Your items</th></tr>
            </thead>
            <tbody>
            {% for item in cart_items %}
            <tr>
                <td><a href="item.product.get_absolute_url"><img src="{{item.product.image.url}}" alt="" class="float-left rounded custom_img" style="width:100px;"></a></td>
                <td class="text-lef">{{item.product.name}}
                    <br>
                    SKU:{{item.product.id}}
                    <br>
                    Price: $ {{item.product.price}}
                    <br>
                    Qnty: {{item.quantity}} X $ {{item.product.price}}
                </td>
                <td>
                    $ {{item.sub_total}}
                </td>
                {% if item.quantity < item.product.stock %}
                <td>
                    <a href="{% url 'cartapp:add_cart' item.product.id %}" class="custom_a"><i class="fa fa-plus custom_icon"></i></a>
                    &nbsp;<a href="{% url 'cartapp:remove_item' item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                    &nbsp;<a href="{% url 'cartapp:delete_item' item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>
                </td>
                {% else %}
                <td>
                    &nbsp;<a href="{% url 'cartapp:remove_item' item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                    &nbsp;<a href="{% url 'cartapp:delete_item' item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>


        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th>
                    Checkout
                </th>
            </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Please review your shopping cart items before proceeding with the order payment</td>
                </tr>
                <tr>
                    <td class="text-left">
                        Your total amount is : <strong>{{total}}</strong>
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="max_auto">
            <a href="{% url 'ecartapp:allProdCat' %}" class="btn btn-secondary btn-block my_custom_btn">Make payment</a>
            &nbsp;<a href="{% url 'ecartapp:allProdCat' %}" class="btn btn-secondary btn-block my_custom_btn">Continue shopping</a>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

dstore/templates/courses.html
<option value="">Select courses</option>
{% for course in courses %}
  <option value="{{ course.pk }}">{{ course.name }}</option>
{% endfor %}

dstore/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


    <!-- Carousel -->
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active" style=" display: flex;justify-content: center;align-items: center;">
                <img src="{% static 'image/art3.png'%}" class="w-50 h-50" alt="...">
            </div>
        </div>
    </div>

    <!-- Featured products -->
    <div class="container my-5">
        <h3 class="text-center mb-4">Featured Products</h3>
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <img class="card-img-top" src="{% static 'image/book1.jpg'%}" height="200" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">Books and notes</h5>
                        <p class="card-text">All products including books ,notebooks ,lab records, notepads are available.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <img class="card-img-top" src="{% static 'image/files.jpg'%}" height="200" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">Files</h5>
                        <p class="card-text">vibrant collection of file holders and exame boards are ready for sale.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <img class="card-img-top" src="{% static 'image/pencile.jpg'%}" height="200" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">Other stationaries</h5>
                        <p class="card-text">All other stationaries including pen, penciles,colours you can buy.</p>
<!--
                        <a href="#" class="btn btn-primary">Buy Now</a>
-->
                    </div>
                </div>
            </div>

        </div>
    </div>

    <!-- Newsletter sign up-->
    <div class="container bg-light bg-gradient mb-10 my-5 text-center py-5">
        <a type="button" class="btn btn-primary" href="{% url 'homeapp:shope' %}">Purchase here</a>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endblock %}

dstore/templates/login.html
{% extends 'base.html' %}
{% block content %}
<style>
      body {
        background-color: #f8f9fa;
      }
      .form-login {
        max-width: 400px;
        margin: 50px auto;
        background-color: #fff;
        box-shadow: 0 3px 6px rgba(0, 0, 0, 0.1);
        padding: 30px;
        border-radius: 5px;
      }
      .form-login h2 {
        text-align: center;
        margin-bottom: 30px;
      }
      .form-login input[type="text"],
      .form-login input[type="password"] {
        border-radius: 20px;
      }
      .form-login input[type="submit"] {
        background-color: #007bff;
        border: none;
        border-radius: 20px;
        padding: 10px 40px;
        color: #fff;
        font-weight: bold;
      }
      .form-login input[type="submit"]:hover {
        background-color: #0069d9;
      }
    </style>
    <div class="vh-100 d-flex align-items-center">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 col-xl-11 mx-auto">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5" style="padding:25px !important;">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Login</p>

                <form action="{% url 'homeapp:login' %}" method="post" class="mx-1 mx-md-4">
                  {% csrf_token%}

                  {% for msg in messages%}
                  <div class="form-group">
                      <div class="col-sm-10">
                        <h4 style="background-color:yellow;">{{msg}}</h4>
                      </div>
                  </div>
                  {% endfor %}



                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <input type="text" id="form3Example1c" name="username" class="form-control" />
                      <label class="form-label" for="form3Example1c">User Name</label>
                    </div>
                  </div>
                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <input type="password" id="form3Example4c" name="password" class="form-control" />
                      <label class="form-label" for="form3Example4c">Password</label>
                    </div>
                  </div>


                  <div class="d-flex justify-content-left mx-4 mb-3 mb-lg-4">
                    <button type="submit" class="btn btn-success btn-lg">login</button>
                    <a href="{% url 'homeapp:register' %}" style="padding-top: 20px;padding-left: 5px;">Not registered yet.</a>
                  </div>

                </form>

              </div>
              <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                  class="img-fluid" alt="Sample image">

              </div>
            </div>
          </div>
        </div>
      </div>
      </div>
    </div>
      </div>
    <!-- Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBVZXp+i/led5ITyI4ZGgWv" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmIaUksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOUdXf3K9gJQvy0Sl5/aCywDmIhLv/lE5JvoRxT2hqU/E3J" crossorigin="anonymous"></script>

{% endblock %}

dstore/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'homeapp:index' %}">Dstore</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto">
        <!--<li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>-->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Departments
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Computer_science">Computer Science</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Commerce">Commerce</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Bachelor_of_Medical_Sciences">Medical Science</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Food_technology">Food Technology</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/English_literature">English Literature</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'homeapp:about' %}">About Us</a>
        </li>
      </ul>
      <ul class="navbar-nav">
        {% if user.is_authenticated %}
          {% if item_count > 0 %}
          <li class="nav-item">
            <a class="nav-link" href="#">

              <a class="nav-link" href="{% url 'cartapp:cart_detail' %}"><i class="bi bi-cart"><span class="badge bg-dark rounded-circle text-white">{{item_count}}</span></i></a>
            </a>
          </li>
          {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'homeapp:logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'homeapp:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'homeapp:register' %}">Register</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

dstore/templates/shope.html
{% extends 'base.html' %}
{% load static %}
{% block content %}






    <div class="container bg-light bg-gradient mb-10 my-5 text-center py-5">

      <section class="h-100">
      <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col">
        <div class="card card-registration my-4">
          <div class="row g-0">
              <div class="card-body p-md-5 text-black">
              <form action="{% url 'cartapp:add_cart' %}" id="profileForm" data-courses-url="{% url 'homeapp:ajax_load_courses' %}" method="post">
                {% csrf_token %}
                <h3 class="mb-5 text-uppercase">Student registration form</h3>


                <div class="row justify-content-center">
                        <!---col1--->
                        <div class="col-md-10 col-lg-6 order-2 order-lg-1">
                          <div class="d-flex flex-row align-items-center mb-4">
                            <div class="form-outline flex-fill mb-0">
                              <label class="form-label" >Name</label>
                              <input type="text"  name="name" class="form-control" required/>
                              <input type="hidden"  name="user" class="form-control"value={{user}} />
                            </div>
                          </div>
                          <div class="d-flex flex-row align-items-center mb-4">
                            <div class="form-outline flex-fill mb-0">
                              <label class="form-label" >DOB</label>
                              <input type="date"  name="dob" class="form-control" required/>
                            </div>
                          </div>
                          <div class="d-flex flex-row align-items-center mb-4">
                            <div class="form-outline flex-fill mb-0">
                              <label class="form-label" >Age</label>
                              <input type="number"  name="age" class="form-control" required/>
                            </div>
                          </div>
                          <div class="d-flex flex-row align-items-center mb-4">
                            <div class="form-outline flex-fill mb-0" style="height:70px;">
                              <label class="form-label" >Gender</label>
                                </br>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input form-control"  type="radio" name="gender"  value="Male">
                                    <label class="form-check-label" style="margin-left:5px;">Male</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input form-control" type="radio" name="gender"  value="Female">
                                    <label class="form-check-label" style="margin-left:5px;">Female</label>
                                </div>

                            </div>
                          </div>
                          <div class="d-flex flex-row align-items-center mb-4">
                            <div class="form-outline flex-fill mb-0">
                              <label class="form-label" >Phone number</label>
                              <input type="text"  name="phone" class="form-control" required/>
                            </div>
                          </div>
                        </div>
                        <!--col 2--->
                        <div class="col-md-10 col-lg-6 order-2 order-lg-1">


                          <div class="d-flex flex-row align-items-center mb-4">
                            <div class="form-outline flex-fill mb-0">
                              <label class="form-label" >Email id</label>
                              <input type="email"  name="email" class="form-control" required/>
                            </div>
                          </div>

                          <div class="d-flex flex-row align-items-center mb-4">
                            <div class="form-outline flex-fill mb-0">
                              <label class="form-label" >Address</label>
                              <input type="text"  name="address" class="form-control" required/>
                            </div>
                          </div>
                          <div class="d-flex flex-row align-items-center mb-4">
                            <div class="form-outline flex-fill mb-0">
                              <label class="form-label" >Department</label>

                              <select class="form-select form-control" id="id_department" name="department" required>
                                  <option value="">Select department</option>
                                  {% for department in departments %}
                                    <option value="{{ department.id }}">{{ department.name }}</option>
                                  {% endfor %}
                              </select>
                            </div>
                          </div>
                          <div class="d-flex flex-row align-items-center mb-4">
                            <div class="form-outline flex-fill mb-0">
                              <label class="form-label" >Courses</label>

                              <select class="form-select form-control" id="id_course" name="course" required>
                                  <option value="">Select course</option>
                                  <!------course will generate here----------------->
                              </select>

                            </div>
                          </div>
                          <div class="d-flex flex-row align-items-center mb-4">
                            <div class="form-outline flex-fill mb-0">
                                <label class="form-label" >Purpose</label>
                                <select class="form-select form-control " name="purpose" id="purpose" required>
                                    <option selected>Select purpose</option>
                                    <option value="enquiry" >Enquiry</option>
                                    <option value="placeorder">Place order</option>
                                    <option value="return">Return</option>
                                </select>
                            </div>
                          </div>


                        </div>
                        </div>
                <div class="row justify-content-center">
                  <div class="col-md-10 col-lg-12 order-2 order-lg-1">
                    <div class="d-flex flex-row align-items-center mb-4">
                            <div class="form-outline flex-fill mb-0">
                              <label class="form-label">Materials provide</label>
                                  <!--products items-->
                              <div class="row justify-content-center">
                                {% for product in products %}
                                <div class="col-md-3">
                                    <div class="wrap w-100">
                                        <div class="card shadow-sm bg-white rounded" style="margin-bottom:10px;">

                                        <div class="card-body" style="height:120px;">
                                        <div class="row">
                                            <div class="col-md-5" style="margin-top:-10px;">
                                            {% if product.image %}
                                            <img class="card-img-top" src="{{product.image.url}}" alt="{{product.name}}" style="height:100px;width:9workon 0px;">
                                            {% endif %}
                                            </div>
                                            <div class="col-md-5">
                                                <p class="card-text"><b>{{product.name}}</b></p><p>${{product.price}}</p>
                                            </div>
                                            <div class="col-md-2">
                                                <input class="products" type="checkbox" id="{{product.id}}" onclick="productChecked()" name="products"  value="{{product.id}}" >
<!--
                                                <a href="" id="plus" onclick="addqnty( {{product.id}} )"  class="text-dark custom_a"><i class="bi bi-cart-plus custom_icon"></i></a>


                                                <a href="{% url 'cartapp:add_item' product.id %}" id="plus" class="text-dark custom_a"><i class="bi bi-cart-plus  custom_icon"></i></a>
                                                <a href="" id="minus" class="text-dark custom_a"><i class="bi bi-cart-dash custom_icon"></i></a>
                                                <span class="badge bg-dark rounded-circle text-white">{{count}}</span>
-->
                                            </div>
                                        </div>
                    </div>

                </div>

            </div>
        </div>
        {% endfor %}
    </div>
                              <!--end products items here-->
                            </div>
                          </div>
                  </div>
                </div>

                <!--message box-->
                <div  class="w-100 shadow-lg p-3 mb-5 bg-white rounded" id="div2" style="display: none;">
                    <p id="msg"></p>
                    <button type="submit"  class="btn btn-success btn-lg ms-2">Home</button>
                </div>

                <div class="d-flex justify-content-end pt-3">

                  <button type="submit" onclick="return showDiv();" class="btn btn-warning btn-lg ms-2">Submit</button>

                </div>

              </form>
            </div>
              </div>


          </div>
        </div>
      </div>
    </div>

</section>



    </div>




    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<script>
    $("#id_department").change(function () {
      var url = $("#profileForm").attr("data-courses-url");
      var departmentId = $(this).val();

      $.ajax({
        url: url,
        data: {
          'department': departmentId
        },
        success: function (data) {
          $("#id_course").html(data);
        }
      });

    });

// get purpose and assign the value to msg
var purpose = document.getElementById("purpose");
var msg = document.getElementById("msg");
var pass;
function onChange() {
   var value = purpose.value;
   var text = purpose.options[purpose.selectedIndex].text;
   console.log(value, text);
   if (value =="enquiry"){
    pass = "Thankyou for enquiry."
   }else if(value =="placeorder"){
    pass = "order confirmed"
   }else{
    pass = "submited succesfully"
   }
   console.log(pass)
   msg.innerHTML = pass;
}
purpose.onchange= onChange;
onChange();



function showDiv() {
   document.getElementById('div2').style.display = 'block';
    return false;
   }



  </script>
{% endblock %}